apiVersion: batch/v1
kind: Job
metadata:
  name: seed-db 
spec:
  template:
    spec:
      containers:
      - name: seed-db
        image: nyuappsec/assign3:v0
        command: ["/bin/sh", "-c"]
        args: ["python3 ../manage.py loaddata ../seed-db.json"]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-pwd
                  key: password

          - name: MYSQL_DB
            value: GiftcardSiteDB

          - name: MYSQL_HOST
            value: mysql-service

          - name: ALLOWED_HOSTS
            value: "*,"

          - name: DJANGO_SECRET_KEY
            valueFrom: 
              secretKeyRef: 
                  name: django-secret-key 
                  key: secretKey 

          - name: ADMIN_UNAME
            valueFrom:
              secretKeyRef:
                  name: admin-login-secrets
                  key: username

          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                  name: admin-login-secrets
                  key: password 
      restartPolicy: Never
  backoffLimit: 4